- name: "Create Namespace {{ k8s_namespace }}"
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ k8s_namespace }}"
