      - name: Create Cloudflare Tunnel Secret
        kubernetes.core.k8s:
          definition:
            apiVersion: v1
            kind: Secret
            metadata:
              name: cloudflare-token
              namespace: "{{ k8s_namespace }}"
            type: Opaque
            stringData:
              tunnel_token: "{{ secrets[env].cloudflare_token }}"

      - name: Create Cloudflare Tunnel Deployment
        kubernetes.core.k8s:
          definition:
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: cloudflared
              namespace: "{{ k8s_namespace }}"
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: cloudflared
              template:
                metadata:
                  labels:
                    app: cloudflared
                spec:
                  containers:
                    - name: cloudflared
                      image: cloudflare/cloudflared:latest
                      args:
                        - tunnel
                        - --no-autoupdate
                        - run
                      env:
                        - name: TUNNEL_TOKEN
                          valueFrom:
                            secretKeyRef:
                              name: cloudflare-token
                              key: tunnel_token
                      resources:
                        requests:
                          cpu: 10m
                          memory: 64Mi
                        limits:
                          cpu: 50m
                          memory: 128Mi
