- name: Create S3 PVC
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app }}-s3-pvc"
        namespace: "{{ k8s_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi

- name: Create S3 Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}-s3"
        namespace: "{{ k8s_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ app }}-s3"
        template:
          metadata:
            labels:
              app: "{{ app }}-s3"
          spec:
            containers:
              - name: minio
                image: minio/minio:latest
                args:
                  - server
                  - /data
                  - --console-address
                  - ":9001"
                envFrom:
                  - secretRef:
                      name: "s3-secrets"
                ports:
                  - containerPort: 9000
                    name: s3-api
                  - containerPort: 9001
                    name: console
                volumeMounts:
                  - name: data
                    mountPath: /data
            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: "{{ app }}-s3-pvc"

- name: Create S3 Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}-s3"
        namespace: "{{ k8s_namespace }}"
      spec:
        selector:
          app: "{{ app }}-s3"
        ports:
          - name: s3-api
            port: 9000
            targetPort: 9000
          - name: console
            port: 9001
            targetPort: 9001

- name: Create S3 Bucket Initialization Job
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ app }}-s3-init-bucket"
        namespace: "{{ k8s_namespace }}"
      spec:
        ttlSecondsAfterFinished: 86400
        template:
          metadata:
            labels:
              app: "{{ app }}-s3-init"
          spec:
            restartPolicy: OnFailure
            containers:
              - name: minio-mc
                image: minio/mc:latest
                envFrom:
                  - secretRef:
                      name: "s3-secrets"
                command:
                  - /bin/sh
                  - -c
                  - |
                    until mc alias set myminio http://{{ app }}-s3:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD; do
                      sleep 2
                    done

                    echo "Create bucket..."
                    mc mb myminio/$MINIO_BUCKET --ignore-existing

                    echo "Bucket create successfully"
