- name: Create S3 PVC
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app }}-s3-pvc"
        namespace: "{{ k8s_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 10Gi

- name: Create S3 Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}-s3"
        namespace: "{{ k8s_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ app }}-s3"
        template:
          metadata:
            labels:
              app: "{{ app }}-s3"
          spec:
            containers:
              - name: minio
                image: minio/minio:latest
                args:
                  - server
                  - /data
                  - --console-address
                  - ":9001"
                envFrom:
                  - secretRef:
                      name: "s3-secrets"
                ports:
                  - containerPort: 9000
                    name: s3-api
                  - containerPort: 9001
                    name: console
                volumeMounts:
                  - name: data
                    mountPath: /data
            volumes:
              - name: data
                persistentVolumeClaim:
                  claimName: "{{ app }}-s3-pvc"

- name: Create S3 Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}-s3"
        namespace: "{{ k8s_namespace }}"
      spec:
        selector:
          app: "{{ app }}-s3"
        ports:
          - name: s3-api
            port: 9000
            targetPort: 9000
          - name: console
            port: 9001
            targetPort: 9001

- name: Create S3 Bucket Initialization Job
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: batch/v1
      kind: Job
      metadata:
        name: "{{ app }}-s3-init-bucket"
        namespace: "{{ k8s_namespace }}"
      spec:
        ttlSecondsAfterFinished: 3600
        template:
          metadata:
            labels:
              app: "{{ app }}-s3-init"
          spec:
            restartPolicy: OnFailure
            containers:
              - name: aws-cli-init
                image: amazon/aws-cli:latest
                envFrom:
                  - secretRef:
                      name: "s3-secrets"
                env:
                  - name: AWS_ACCESS_KEY_ID
                    valueFrom:
                      secretKeyRef:
                        name: "s3-secrets"
                        key: MINIO_ROOT_USER
                  - name: AWS_SECRET_ACCESS_KEY
                    valueFrom:
                      secretKeyRef:
                        name: "s3-secrets"
                        key: MINIO_ROOT_PASSWORD
                command:
                  - /bin/sh
                  - -c
                  - |
                    ENDPOINT="http://{{ app }}-s3:9000"

                    echo "1. Waiting for S3 server to be ready..."
                    until aws s3 ls --endpoint-url $ENDPOINT > /dev/null 2>&1; do
                      sleep 2
                    done

                    echo "2. Create bucket..."
                    aws s3 mb s3://$MINIO_BUCKET --endpoint-url $ENDPOINT || true

                    echo "3. Create CORS policy file dynamically..."
                    cat <<EOF > cors.json
                    {
                      "CORSRules": [
                        {
                          "AllowedHeaders": ["*"],
                          "AllowedMethods": ["GET", "HEAD"],
                          "AllowedOrigins": ["https://audiohub.art",],
                          "ExposeHeaders": []
                        }
                      ]
                    }
                    EOF

                    echo "4. Apply CORS policy..."
                    aws s3api put-bucket-cors \
                      --bucket $MINIO_BUCKET \
                      --cors-configuration file://cors.json \
                      --endpoint-url $ENDPOINT

                    echo "Bucket initialized and CORS configured success
