- name: Create s3 secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "s3-secrets"
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      stringData:
        MINIO_ROOT_USER: "{{ secrets[env].s3.access_key }}"
        MINIO_ROOT_PASSWORD: "{{ secrets[env].s3.secret_key }}"
        MINIO_BUCKET: "{{ secrets[env].s3.bucket }}"
