- name: Create Backend secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-backend-secrets"
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      stringData:
        DATABASE_URL: "postgresql://{{ app }}:{{ secrets[env].db.password }}@{{ app }}-db:5432/{{ app }}"
        JWT_ACCESS_SECRET: "{{ secrets[env].backend.access_secret }}"
        JWT_REFRESH_SECRET: "{{ secrets[env].backend.refresh_secret }}"
        S3_ENDPOINT: "{{ app }}-s3:9000"
        S3_ACCESS_KEY: "{{ secrets[env].s3.access_key }}"
        S3_SECRET_KEY: "{{ secrets[env].s3.secret_key }}"
        S3_BUCKET_NAME: "{{ secrets[env].s3.bucket }}"
