- name: Create service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}-frontend"
        namespace: "{{ k8s_namespace }}"
      spec:
        selector:
          app: "{{ app }}-frontend"
        ports:
          - name: "{{ app }}-svc-port"
            protocol: TCP
            port: 80
            targetPort: 3000

- name: Create Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}-frontend"
        namespace: "{{ k8s_namespace }}"
      spec:
        replicas: 1
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        selector:
          matchLabels:
            app: "{{ app }}-frontend"
        template:
          metadata:
            labels:
              app: "{{ app }}-frontend"
          spec:
            containers:
              - image: "{{ image }}:{{ version }}"
                imagePullPolicy: Always
                name: "{{ app }}-frontend"
                ports:
                  - containerPort: 3000
                envFrom:
                  - secretRef:
                      name: "{{ app }}-frontend-secrets"
                resources:
                  requests:
                    cpu: 50m
                    memory: 120Mi
                  limits:
                    cpu: 200m
                    memory: 512Mi
                readinessProbe:
                  tcpSocket:
                    port: 3000
                  initialDelaySeconds: 5
                  timeoutSeconds: 3
