- name: Ensure Secrets
  include_tasks:
    file: secrets.yml
    apply:
      tags:
        - frontend.secrets
  tags:
    - frontend.secrets

- name: Deploy frontend
  include_tasks:
    file: frontend.yml
    apply:
      tags:
        - frontend.frontend
  tags:
    - frontend.frontend
