- name: Create frontend secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "{{ app }}-frontend-secrets"
        namespace: "{{ k8s_namespace }}"
      type: Opaque
      stringData:
        BACKEND_URL: "http://{{ app }}-backend.{{ k8s_namespace }}.svc.cluster.local:80"
        AUTH_SECRET: "{{ secrets[env].frontend.secret }}"
        AUTH_TRUST_HOST: "true"
