- name: Create Persistent Volume Claim (Le disque dur de la DB)
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "{{ app }}-db-pvc"
        namespace: "{{ k8s_namespace }}"
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi

- name: Create PostgreSQL Deployment
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "{{ app }}-db"
        namespace: "{{ k8s_namespace }}"
      spec:
        replicas: 1
        selector:
          matchLabels:
            app: "{{ app }}-db"
        template:
          metadata:
            labels:
              app: "{{ app }}-db"
          spec:
            containers:
              - name: postgres
                image: postgres:15-alpine
                ports:
                  - containerPort: 5432
                env:
                  - name: POSTGRES_USER
                    valueFrom:
                      secretKeyRef:
                        name: "{{ app }}-db-credentials"
                        key: username
                  - name: POSTGRES_PASSWORD
                    valueFrom:
                      secretKeyRef:
                        name: "{{ app }}-db-credentials"
                        key: password
                  - name: POSTGRES_DB
                    valueFrom:
                      secretKeyRef:
                        name: "{{ app }}-db-credentials"
                        key: database
                volumeMounts:
                  - name: pg-data
                    mountPath: /var/lib/postgresql/data
            volumes:
              - name: pg-data
                persistentVolumeClaim:
                  claimName: "{{ app }}-db-pvc"

- name: Create PostgreSQL Service
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app }}-db"
        namespace: "{{ k8s_namespace }}"
      spec:
        selector:
          app: "{{ app }}-db"
        ports:
          - name: postgres
            protocol: TCP
            port: 5432
            targetPort: 5432
